app:
  mode: debug 
  supertoken: ed01a970cbf2d5c5438e36361c9cb36f1580
service:
  stoken:
    url: http://api.storybox-dev.svc.roobo.net
card:
  redis:
    name: card
    host: redis
    port: 6379
    password: 
    db: 0
  database:
    name: card
    type: mysql
    host: mysql
    port: 3306
    user: root
    target: identify
    password: 123456
    maxIdle: 10 
    maxOpen: 5 
    showsql: True
    location: Asia/Shanghai
  ipc:
    img: ../images
  rpc:
    host: thrift 
    port: 9090 
    img: ../images
