app:
  mode: debug 
card:
  redis:
    name: card
    host: redis
    port: 6379
    password: 
    db: 0
  database:
    name: card
    type: mysql
    host: mysql
    port: 3306
    user: root
    target: card
    password: 123456
    maxIdle: 10 
    maxOpen: 5 
    showsql: True
    location: Asia/Shanghai
  ipc:
    img: ../images
  rpc:
    host: thrift 
    port: 9090 
    img: ../images
