/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef ImageService_H
#define ImageService_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include "image_types.h"

namespace image {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class ImageServiceIf {
 public:
  virtual ~ImageServiceIf() {}
  virtual void getIdentify(Response& _return, const Request& request) = 0;
};

class ImageServiceIfFactory {
 public:
  typedef ImageServiceIf Handler;

  virtual ~ImageServiceIfFactory() {}

  virtual ImageServiceIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(ImageServiceIf* /* handler */) = 0;
};

class ImageServiceIfSingletonFactory : virtual public ImageServiceIfFactory {
 public:
  ImageServiceIfSingletonFactory(const ::apache::thrift::stdcxx::shared_ptr<ImageServiceIf>& iface) : iface_(iface) {}
  virtual ~ImageServiceIfSingletonFactory() {}

  virtual ImageServiceIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(ImageServiceIf* /* handler */) {}

 protected:
  ::apache::thrift::stdcxx::shared_ptr<ImageServiceIf> iface_;
};

class ImageServiceNull : virtual public ImageServiceIf {
 public:
  virtual ~ImageServiceNull() {}
  void getIdentify(Response& /* _return */, const Request& /* request */) {
    return;
  }
};

typedef struct _ImageService_getIdentify_args__isset {
  _ImageService_getIdentify_args__isset() : request(false) {}
  bool request :1;
} _ImageService_getIdentify_args__isset;

class ImageService_getIdentify_args {
 public:

  ImageService_getIdentify_args(const ImageService_getIdentify_args&);
  ImageService_getIdentify_args& operator=(const ImageService_getIdentify_args&);
  ImageService_getIdentify_args() {
  }

  virtual ~ImageService_getIdentify_args() throw();
  Request request;

  _ImageService_getIdentify_args__isset __isset;

  void __set_request(const Request& val);

  bool operator == (const ImageService_getIdentify_args & rhs) const
  {
    if (!(request == rhs.request))
      return false;
    return true;
  }
  bool operator != (const ImageService_getIdentify_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ImageService_getIdentify_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class ImageService_getIdentify_pargs {
 public:


  virtual ~ImageService_getIdentify_pargs() throw();
  const Request* request;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ImageService_getIdentify_result__isset {
  _ImageService_getIdentify_result__isset() : success(false) {}
  bool success :1;
} _ImageService_getIdentify_result__isset;

class ImageService_getIdentify_result {
 public:

  ImageService_getIdentify_result(const ImageService_getIdentify_result&);
  ImageService_getIdentify_result& operator=(const ImageService_getIdentify_result&);
  ImageService_getIdentify_result() {
  }

  virtual ~ImageService_getIdentify_result() throw();
  Response success;

  _ImageService_getIdentify_result__isset __isset;

  void __set_success(const Response& val);

  bool operator == (const ImageService_getIdentify_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const ImageService_getIdentify_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const ImageService_getIdentify_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _ImageService_getIdentify_presult__isset {
  _ImageService_getIdentify_presult__isset() : success(false) {}
  bool success :1;
} _ImageService_getIdentify_presult__isset;

class ImageService_getIdentify_presult {
 public:


  virtual ~ImageService_getIdentify_presult() throw();
  Response* success;

  _ImageService_getIdentify_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class ImageServiceClient : virtual public ImageServiceIf {
 public:
  ImageServiceClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  ImageServiceClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void getIdentify(Response& _return, const Request& request);
  void send_getIdentify(const Request& request);
  void recv_getIdentify(Response& _return);
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class ImageServiceProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::apache::thrift::stdcxx::shared_ptr<ImageServiceIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (ImageServiceProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_getIdentify(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  ImageServiceProcessor(::apache::thrift::stdcxx::shared_ptr<ImageServiceIf> iface) :
    iface_(iface) {
    processMap_["getIdentify"] = &ImageServiceProcessor::process_getIdentify;
  }

  virtual ~ImageServiceProcessor() {}
};

class ImageServiceProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  ImageServiceProcessorFactory(const ::apache::thrift::stdcxx::shared_ptr< ImageServiceIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::apache::thrift::stdcxx::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::apache::thrift::stdcxx::shared_ptr< ImageServiceIfFactory > handlerFactory_;
};

class ImageServiceMultiface : virtual public ImageServiceIf {
 public:
  ImageServiceMultiface(std::vector<apache::thrift::stdcxx::shared_ptr<ImageServiceIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~ImageServiceMultiface() {}
 protected:
  std::vector<apache::thrift::stdcxx::shared_ptr<ImageServiceIf> > ifaces_;
  ImageServiceMultiface() {}
  void add(::apache::thrift::stdcxx::shared_ptr<ImageServiceIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void getIdentify(Response& _return, const Request& request) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->getIdentify(_return, request);
    }
    ifaces_[i]->getIdentify(_return, request);
    return;
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class ImageServiceConcurrentClient : virtual public ImageServiceIf {
 public:
  ImageServiceConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  ImageServiceConcurrentClient(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void getIdentify(Response& _return, const Request& request);
  int32_t send_getIdentify(const Request& request);
  void recv_getIdentify(Response& _return, const int32_t seqid);
 protected:
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  apache::thrift::stdcxx::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  ::apache::thrift::async::TConcurrentClientSyncInfo sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

} // namespace

#endif
