/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "image_constants.h"

namespace image {

const imageConstants g_image_constants;

imageConstants::imageConstants() {
}

} // namespace

