/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef image_CONSTANTS_H
#define image_CONSTANTS_H

#include "image_types.h"

namespace image {

class imageConstants {
 public:
  imageConstants();

};

extern const imageConstants g_image_constants;

} // namespace

#endif
