/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef image_TYPES_H
#define image_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/stdcxx.h>


namespace image {

struct ResponseState {
  enum type {
    StateOk = 0,
    StateError = 1,
    StateEmpty = 2
  };
};

extern const std::map<int, const char*> _ResponseState_VALUES_TO_NAMES;

std::ostream& operator<<(std::ostream& out, const ResponseState::type& val);

class Request;

class Response;

typedef struct _Request__isset {
  _Request__isset() : imgPath(false), app(false), projectType(false) {}
  bool imgPath :1;
  bool app :1;
  bool projectType :1;
} _Request__isset;

class Request : public virtual ::apache::thrift::TBase {
 public:

  Request(const Request&);
  Request& operator=(const Request&);
  Request() : imgPath(), app(), projectType(0) {
  }

  virtual ~Request() throw();
  std::string imgPath;
  std::string app;
  int32_t projectType;

  _Request__isset __isset;

  void __set_imgPath(const std::string& val);

  void __set_app(const std::string& val);

  void __set_projectType(const int32_t val);

  bool operator == (const Request & rhs) const
  {
    if (!(imgPath == rhs.imgPath))
      return false;
    if (!(app == rhs.app))
      return false;
    if (!(projectType == rhs.projectType))
      return false;
    return true;
  }
  bool operator != (const Request &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Request & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(Request &a, Request &b);

std::ostream& operator<<(std::ostream& out, const Request& obj);

typedef struct _Response__isset {
  _Response__isset() : bookID(true), state(false) {}
  bool bookID :1;
  bool state :1;
} _Response__isset;

class Response : public virtual ::apache::thrift::TBase {
 public:

  Response(const Response&);
  Response& operator=(const Response&);
  Response() : bookID(0), state((ResponseState::type)0) {
  }

  virtual ~Response() throw();
  int32_t bookID;
  ResponseState::type state;

  _Response__isset __isset;

  void __set_bookID(const int32_t val);

  void __set_state(const ResponseState::type val);

  bool operator == (const Response & rhs) const
  {
    if (!(bookID == rhs.bookID))
      return false;
    if (!(state == rhs.state))
      return false;
    return true;
  }
  bool operator != (const Response &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Response & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(Response &a, Response &b);

std::ostream& operator<<(std::ostream& out, const Response& obj);

} // namespace

#endif
