version: '2'
services:
  redis:
    image: redis:3.2
    container_name: ${PROJECT_NAME}-${DEV_USER}-redis
    expose:
      - "6379"
  mysql:
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    image: mysql:5.6.38
    container_name: ${PROJECT_NAME}-${DEV_USER}-mysql
    volumes:
      - /home/${DEV_USER}/database/mysql:/var/lib/mysql
    ports:
      - "${DEV_DB_PORT}:3306"
    networks:
      - default
  thrift:
    image: ${IMG_PREFIX}identify:thrift-0.11
    container_name: ${PROJECT_NAME}-${DEV_USER}-thrift
    volumes:
      # 挂载项目代码目录
      - ../release/server:/home/roobo/thrift/server
      - ../images:/home/roobo/images
      - ../build/model:/home/roobo/thrift/model
    working_dir: /home/roobo/thrift
    entrypoint: 
      - ./server 
    expose:
      - "9090"
    networks:
      - default
  backend:
    environment:
      - ConfigPath=./config/config.yaml
    image: ${IMG_PREFIX}identify:golang-1.10 
    container_name: ${PROJECT_NAME}-${DEV_USER}-golang
    volumes:
      # 挂载项目代码目录
      - ../backend:/go/src/identify/backend
      - ../images:/go/src/identify/images
    working_dir: /go/src/identify/backend
    entrypoint: 
      - bee 
      - run 
    links:
      - mysql:mysql.localhost
    ports:
      - "${DEV_PORT}:8080"
    networks:
      - default
networks:
  default:
    external:
      name: ${DEV_USER}
