FROM golang:1.10

COPY ./release/backend /go/src/identify/backend
COPY ./release/tool /go/src/tool/tool
COPY ./hack/release/config.yaml /go/src/config/.config.yaml
RUN mkdir /go/src/identify/logs

WORKDIR /go/src/identify

CMD ["./backend"]
